env:
  global:
    - CC_TEST_REPORTER_ID=8ca21f9a3cc44ce5cc9ac86f18257e6c18656901692f65cb1fd13aae09480a26
language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules # NPM packages
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    else
      echo Error:TRAVIS_OS_NAME && exit 1;
    fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: change
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm install nyc codecov
  - ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls
  - codecov -f coverage/*.json
