language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules # NPM packages
script:
  - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: change
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
